// This file was generated by PermissionsDispatcher. Do not modify!
package fashiome.android.v2.fragments;

import android.app.Activity;
import android.content.Context;
import android.support.v4.app.ActivityCompat;
import fashiome.android.v2.fragments.ProductMapFragment;
import permissions.dispatcher.PermissionUtils;


/**
 * Created by rakhe on 3/5/2016.
 */
final class MapActivityPermissionDispatcher {

    private static final int REQUEST_GETMYLOCATION = 0;

    private static final String[] PERMISSION_GETMYLOCATION = new String[] {"android.permission.ACCESS_FINE_LOCATION","android.permission.ACCESS_COARSE_LOCATION"};

    private MapActivityPermissionDispatcher() {
    }

    static void getMyLocationWithCheck(ProductMapFragment target, Activity c) {
        if (PermissionUtils.hasSelfPermissions(c, PERMISSION_GETMYLOCATION)) {
            target.getMyLocation();
        } else {
            ActivityCompat.requestPermissions(c, PERMISSION_GETMYLOCATION, REQUEST_GETMYLOCATION);
        }
    }

    protected static void onRequestPermissionsResult(ProductMapFragment target, Activity c, int requestCode, int[] grantResults) {
        switch (requestCode) {
            case REQUEST_GETMYLOCATION:
                if (PermissionUtils.getTargetSdkVersion(c) < 23 && !PermissionUtils.hasSelfPermissions(c, PERMISSION_GETMYLOCATION)) {
                    return;
                }
                if (PermissionUtils.verifyPermissions(grantResults)) {
                    target.getMyLocation();
                }
                break;
            default:
                break;
        }
    }
}

